import { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const Square = () => {
    const [values, setValues] = useState({});
    const [selectedItems, setSelectedItems] = useState([]);
    const [activeTab, setActiveTab] = useState('General'); // 👈 for switching tabs

    const handleChange = (e, itemName) => {
        const value = e.target.value;
        if (value === '' || /^[0-9]\d*$/.test(value)) {
            setValues(prev => ({
                ...prev,
                [itemName]: value
            }));
        }
    };

    const handleSelect = (itemName, itemType) => {
        const quantity = parseInt(values[itemName], 10);
        if (quantity && quantity > 0) {
            setSelectedItems(prev => {
                const existing = prev.find(item => item.name === itemName);
                const newItem = { name: itemName, type: itemType, quantity };
                if (existing) {
                    return prev.map(item =>
                        item.name === itemName ? newItem : item
                    );
                } else {
                    return [...prev, newItem];
                }
            });
        }
    };

    // 🛠️ Update the quantity safely even when it's temporarily empty
    const handleUpdateSelectedItem = (e, itemName) => {
        const value = e.target.value;
        if (value === '' || /^[0-9]+$/.test(value)) {
            setSelectedItems(prevItems =>
                prevItems.map(item =>
                    item.name === itemName ? { ...item, quantity: value } : item
                )
            );
        }
    };

    // 🧾 Generate PDF while filtering out empty or zero-quantity items
    const handleBuyNow = () => {
        const filteredItems = selectedItems.filter(item => item.quantity && parseInt(item.quantity) > 0);

        if (filteredItems.length === 0) {
            alert("No valid items to generate PDF!");
            return;
        }

        const doc = new jsPDF();
        let yPosition = 10;
        const pageHeight = doc.internal.pageSize.height;

        doc.setFontSize(20);
        doc.setTextColor('Black');
        doc.text("Niaz Pharmacy", 10, yPosition);
        yPosition += 10;

        const date = new Date().toLocaleDateString();
        doc.setFontSize(12);
        doc.text(`Date: ${date}`, 200, 10, { align: 'right' });

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text("Square Pharmaceuticals Ltd.", 10, yPosition);
        yPosition += 12;

        doc.setFontSize(12);
        doc.setTextColor('black');
        doc.setFont('helvetica', 'bold');
        doc.text("Items Name", 10, yPosition);
        doc.text("Quantity", 105, yPosition, { align: 'center' });
        yPosition += 5;
        doc.line(5, yPosition, 200, yPosition);
        yPosition += 8;

        doc.setFont('helvetica', 'normal');

        filteredItems.forEach(item => {
            if (yPosition > pageHeight - 20) {
                doc.addPage();
                yPosition = 10;

                // Add header on new page
                doc.setFontSize(12);
                doc.setFont('helvetica', 'bold');
                doc.text("Items Name", 10, yPosition);
                doc.text("Quantity", 105, yPosition, { align: 'center' });
                yPosition += 5;
                doc.line(5, yPosition, 200, yPosition);
                yPosition += 8;
                doc.setFont('helvetica', 'normal');
            }

            doc.text(item.name, 10, yPosition);
            const quantityWidth = doc.getTextWidth(item.quantity.toString());
            const quantityX = 105 - quantityWidth;
            doc.text(item.quantity.toString(), quantityX, yPosition);
            yPosition += 10;
        });

        doc.save(`Square-${activeTab.toLowerCase()}.pdf`);
    };

    // Sort items alphabetically
    const generalItems = [
        { name: "Ace Tab 500 mg" },
        { name: "Ace Pediatric Drop 30 ml" },
        { name: "Ace Suppository 125 mg" },
        { name: "Ace Suppository 250 mg" },
        { name: "Ace Suppository 500 mg" },
        { name: "Ace Syp 60 ml (Raspberry)" },
        { name: "Ace Syp 60 ml (Mango)" },
        { name: "Ace Syp 60 ml (Orange)" },
        { name: "Ace Plus Tab 500 mg+65 mg" },
        { name: "Ace Power Tab 1000 mg" },
        { name: "Ace XR Tab 665 mg" },
        { name: "Adryl Syp 100 ml" },
        { name: "Adsalt Tab 300 mg" },
        { name: "Afun Cream 1%" },
        { name: "Alacot Eye Drop 0.1%" },
        { name: "Alacot DS Eye Drop 0.2%" },
        { name: "Alacot Max Eye Drop 0.7%" },
        { name: "Alarid Tab 1 mg" },
        { name: "Alarid Syp 100 ml" },
        { name: "Alarid Eye Drop 0.025%" },
        { name: "Alatrol Tab 10 mg" },
        { name: "Alatrol Syp 60 ml" },
        { name: "Alatrol Paediatric Drop 2.5 mg/ml" },
        { name: "Alenvir Tab 25 mg" },
        { name: "Alice Tab 6 mg" },
        { name: "Alice Tab 12 mg" },
        { name: "Alice Lotion 0.5%" },
        { name: "Almex Chewable Tab 400 mg" },
        { name: "Almex Suspension 10 ml" },
        { name: "Ambrisan Tab 5 mg" },
        { name: "Ambrox Syp 100 ml" },
        { name: "Ambrox Paediatric Drop 15 ml" },
        { name: "Ambrox SR Cap 75 mg" },
        { name: "Amodis Tab 400 mg" },
        { name: "Amodis Suspension 60 ml" },
        { name: "Anadol Suppository 100 mg" },
        { name: "Anadol Cap 50 mg" },
        { name: "Anadol Injection 100 mg/2 ml" },
        { name: "Anadol Plus Tab 325 mg+37.5 mg" },
        { name: "Anadol SR Cap 100 mg" },
        { name: "Anclog Tab 75 mg" },
        { name: "Anclog Plus Tab 75 mg+75 mg" },
        { name: "Anema Rectal Saline 133 ml" },
        { name: "Angilock Tab 100 mg" },
        { name: "Angilock Tab 25 mg" },
        { name: "Angilock Tab 50 mg" },
        { name: "Angilock Plus Tab 100 mg+12.5 mg" },
        { name: "Angilock Plus Tab 100 mg+25 mg" },
        { name: "Angilock Plus Tab 50 mg+12.5 mg" },
        { name: "Angivent MR Tab 35 mg" },
        { name: "Anleptic Suspension 100 ml" },
        { name: "Anleptic CR Tab 200 mg" },
        { name: "Anril Spray" },
        { name: "Anril SR Tab 2.6 mg" },
        { name: "Antazol Nasal Drop 0.05%" },
        { name: "Antazol Nasal Drop 0.1%" },
        { name: "Antazol Plus Nasal Spray" },
        { name: "Antista Syp 100 ml" },
        { name: "Anzitor Tab 20 mg" },
        { name: "Anzitor Tab 10 mg" },
        { name: "Anzitor Tab 40 mg" },
        { name: "Anzitor EZ Tab 10 mg+10 mg" },
        { name: "Anzitor EZ Tab 20 mg+10 mg" },
        { name: "Apsol Oral Paste 5%" },
        { name: "Ariprex Tab 10 mg" },
        { name: "Ariprex Oral Solution 50 ml" },
        { name: "Ariprex Tab 2 mg" },
        { name: "Asynta Suspension 200 ml" },
        { name: "Asynta Chewable Tab" },
        { name: "Asynta Max Chewable Tab" },
        { name: "Asynta Max Suspension" },
        { name: "Avaspray Nasal Spray" },
        { name: "B- 50 Forte Cap" },
        { name: "B-50 Forte Injection" },
        { name: "B - 50 Forte Syp 200 ml" },
        { name: "B - 9 Oral Solution 100 ml" },
        { name: "Bactrocin Ointment 2 %" },
        { name: "Barif Tab 40 mg" },
        { name: "Baritor Tab 2 mg" },
        { name: "Beclomin Inhaler 250 mcg / puff" },
        { name: "Beclomin Inhaler 100 mcg / puff" },
        { name: "Becospray Nasal Spray 50 mcg / spray" },
        { name: "Benostar Mouthwash 250 ml" },
        { name: "Benzapen Injection" },
        { name: "Betameson Cream 0.05 %" },
        { name: "Betameson Ointment 0.05 %" },
        { name: "Betameson - CL Cream" },
        { name: "Betameson - N Cream" },
        { name: "BetriXa Cap 80 mg" },
        { name: "BetriXa Cap 40 mg" },
        { name: "Beviprex Inhaler(9 mcg + 4.8 mcg) / puff" },
        { name: "Bicozin Tab" },
        { name: "Bicozin Syp 100 ml" },
        { name: "Bicozin - I Syp 100 ml" },
        { name: "Bilista Tab 20 mg" },
        { name: "Bilista Kids Tab 10 mg" },
        { name: "Bilista Syp" },
        { name: "Bisocam Tab 2.5 mg + 5 mg" },
        { name: "Bisocor Tab 5 mg" },
        { name: "Bisocor Tab 2.5 mg" },
        { name: "Bisocor Plus Tab 5 mg + 6.25 mg" },
        { name: "Bisocor Plus Tab 2.5 mg + 6.25 mg" },
        { name: "Brofex Syp 100 ml" },
        { name: "Brofex TS Extend Release Suspension 100 ml" },
        { name: "Bromolac Tab 2.5 mg" },
        { name: "Bufocort Inhalation Cap 400 mcg" },
        { name: "Bufocort Inhalation Cap 200 mcg" },
        { name: "Burna Cream 1 %" },
        { name: "Caberol Tab 0.5 mg" },
        { name: "Calbo Tab 500 mg" },
        { name: "Calbo Forte Tab" },
        { name: "Calbo Jr Chewable Tab 250 mg" },
        { name: "Calbo-C Tab" },
        { name: "Calbo-D Tab 500 mg" },
        { name: "Calbo-D Vita Tab" },
        { name: "Calboplex Tab" },
        { name: "Calboral-D Tab 500 mg" },
        { name: "Calboral-DX Tab 600 mg" },
        { name: "Calbostar Tab 740 mg" },
        { name: "Calbostar Tab 400 mg" },
        { name: "Calbotol Tab 1200 mg+0.25 mcg" },
        { name: "Calcitrol Cap 0.25 mcg" },
        { name: "Caloprid Tab 1 mg" },
        { name: "Caloprid Tab 2 mg" },
        { name: "Camlodin Tab 5 mg" },
        { name: "Camlodin Plus Tab 5 mg+25 mg" },
        { name: "Camlodin Plus Tab 5 mg+50 mg" },
        { name: "Camlosart Tab 5 mg+20 mg" },
        { name: "Camlosart Tab 5 mg+40 mg" },
        { name: "Camlotel Tab 5 mg+40 mg" },
        { name: "Camlotel Tab 5 mg+80 mg" },
        { name: "Canaglif Tab 100 mg" },
        { name: "Candex Suspension 30 ml" },
        { name: "Carbizol Tab 10 mg" },
        { name: "Carbizol Tab 5 mg" },
        { name: "Carva Tab 75 mg" },
        { name: "Cavir Tab 1 mg" },
        { name: "Cavir Tab 0.5 mg" },
        { name: "Ceevit Syp 100 ml" },
        { name: "Ceevit Chewable Tab 250 mg" },
        { name: "Ceevit DS Chewable Tab 500 mg" },
        { name: "Ceevit Forte Tab 1000 mg" },
        { name: "Cef-3 Pediatric Drop 21 ml" },
        { name: "Cef-3 Cap 200 mg" },
        { name: "Cef-3 Suspension 30 ml" },
        { name: "Cef-3 DS Cap 400 mg" },
        { name: "Cef-3 Forte Suspension 50 ml" },
        { name: "Cef-3 Max Pediatric Drop 20 ml" },
        { name: "Cef-3 Suspension 50 ml" },
        { name: "Cefotil Tab 250 mg" },
        { name: "Cefotil Tab 500 mg" },
        { name: "Cefotil Suspension 70 ml" },
        { name: "Cefotil Plus Tab 500 mg+125 mg" },
        { name: "Cefotil Plus Suspension 70 ml" },
        { name: "Cefotil Plus Tab 250 mg+62.5 mg" },
        { name: "Ceftiben Suspension 60 ml" },
        { name: "Ceftiben Cap 400 mg" },
        { name: "Cerevas Tab 5 mg" },
        { name: "Cilosta Tab 100 mg" },
        { name: "Cinaron Tab 15 mg" },
        { name: "Cinaron Plus Tab 20 mg+40 mg" },
        { name: "Ciprocin Suspension 60 ml" },
        { name: "Ciprocin Tab 750 mg" },
        { name: "Ciprocin Tab 500 mg" },
        { name: "Ciprocin Tab 250 mg" },
        { name: "Ciprocin Eye Drop 0.3%" },
        { name: "Citivas Tab 500 mg" },
        { name: "Climycin Cap 300 mg" },
        { name: "Clinface Topical Gel" },
        { name: "Clofenac Suppository 12.5 mg" },
        { name: "Clofenac Gel 1%" },
        { name: "Clofenac Suppository 50 mg" },
        { name: "Clofenac Suppository 25 mg" },
        { name: "Clofenac Tab 50 mg" },
        { name: "Clofenac DT Tab 46.5 mg" },
        { name: "Clofenac Plus Injection (75 mg+20 mg)/2 ml" },
        { name: "Clofenac SR Tab 100 mg" },
        { name: "Clopirox Shampoo 1% 100 ml" },
        { name: "Clopirox Cream 1%" },
        { name: "Colicon Tab 10 mg" },
        { name: "Colicon Syp 50 ml" },
        { name: "Colimax Tab 0.6 mg" },
        { name: "Combicid Cream" },
        { name: "Comet Tab 850 mg" },
        { name: "Comet Tab 500 mg" },
        { name: "Comet XR Tab 1 mg" },
        { name: "Comet XR Tab 500 mg" },
        { name: "Comprid Tab 80 mg" },
        { name: "Comprid XR Tab 60 mg" },
        { name: "Comprid XR Tab 30 mg" },
        { name: "Contilex Tab 250 mg+200 mg" },
        { name: "Contilex TS Tab 750 mg+600 mg" },
        { name: "Cotrim Suspension 60 ml" },
        { name: "Cotrim Tab 400 mg+80 mg" },
        { name: "Cotrim DS Tab 800 mg+160 mg" },
        { name: "Cozycol Tab 800 mg" },
        { name: "D-Balance Oral Solution 2000 IU/ml 50 ml" },
        { name: "D-Balance Injection 200000 IU" },
        { name: "D-Balance Cap 20000 IU" },
        { name: "D-Balance Cap 40000 IU" },
        { name: "D-Balance Cap 2000 IU" },
        { name: "D-Balance Cap 50000 IU" },
        { name: "Daizy Tab 2 mg" },
        { name: "De-Rash Ointment" },
        { name: "De-Rash Plus Ointment" },
        { name: "Deflacort Tab 24 mg" },
        { name: "Deflacort Tab 18 mg" },
        { name: "Deflacort Tab 30 mg" },
        { name: "Deflacort Suspension 60 ml" },
        { name: "Deflacort Tab 6 mg" },
        { name: "Depram Tab 25 mg" },
        { name: "Deprex Tab 5 mg" },
        { name: "Deprex Tab 10 mg" },
        { name: "Dermasol Ointment" },
        { name: "Dermasol Cream" },
        { name: "Dermasol Plus Ointment" },
        { name: "Dermasol-N Cream" },
        { name: "Dermasol-N Ointment" },
        { name: "Dermasol-S Scalp Solution 25 ml" },
        { name: "Dexonex Tab 0.5 mg" },
        { name: "Dexonex-C Eye Drop" },
        { name: "Dibenol Tab 5 mg" },
        { name: "Diliner DR DR Cap 20 mg" },
        { name: "Diliner DR DR Cap 60 mg" },
        { name: "Diltizem SR Tab 90 mg" },
        { name: "Dormitol Tab 7.5 mg" },
        { name: "Dotfix Tab 2 mg" },
        { name: "Dotfix Tab 1 mg" },
        { name: "Doxacil Cap 100 mg" },
        { name: "Dubarel Syp 200 ml" },
        { name: "Dulamet Inhaler (100 mcg+5 mcg)/puff" },
        { name: "Dulamet Inhaler (200 mcg+5 mcg)/puff" },
        { name: "Dumeg Tab 500 mg" },
        { name: "Duolax Emulsion 100 ml" },
        { name: "Dyvon Ointment" },
        { name: "Dyvon Plus Ointment" },
        { name: "Dyvon Plus Suspension 25 ml" },
        { name: "Efaxim Tab 200 mg" },
        { name: "Efaxim Tab 550 mg" },
        { name: "Elorim Cream 13.9%" },
        { name: "Emcil Tab 200 mg" },
        { name: "Emjard Tab 10 mg" },
        { name: "Emjard Tab 25 mg" },
        { name: "Emjard M Tab 12.5 mg+500 mg" },
        { name: "Emjard M Tab 5 mg+500 mg" },
        { name: "Emjard M XR Tab 10 mg+1000 mg" },
        { name: "Emjard M XR Tab 5 mg+1000 mg" },
        { name: "Emjard M XR Tab 25 mg+1000 mg" },
        { name: "Emolent Cream" },
        { name: "Emolent Lotion" },
        { name: "Emolent Plus Cream" },
        { name: "Emoli Lotion 100 ml" },
        { name: "Entacyd Suspension 200 ml" },
        { name: "Entacyd Plus Chewable Tab" },
        { name: "Entacyd Plus Suspension 200 ml" },
        { name: "Epitra Tab 1 mg" },
        { name: "Epitra Tab 0.5 mg" },
        { name: "Epitra Tab 2 mg" },
        { name: "Equra Cream 10%" },
        { name: "Erian Suppository" },
        { name: "Erian Ointment" },
        { name: "Eromycin Lotion 3% 25 ml" },
        { name: "Eromycin Suspension 100 ml" },
        { name: "Eromycin Pediatric Drop" },
        { name: "Eromycin DS Tab 500 mg" },
        { name: "Esloric Tab 100 mg" },
        { name: "Eyevi Cap" },
        { name: "Ezex Ointment 0.05%" },
        { name: "Ezex Cream 0.05%" },
        { name: "Facticin Tab 320 mg" },
        { name: "Famotack Suspension 50 ml" },
        { name: "Famotack Tab 20 mg" },
        { name: "Famotack Tab 40 mg" },
        { name: "Femastin Vaginal Cream 0.1%" },
        { name: "Femotol Cap 30 mg" },
        { name: "Fentizol VT Vaginal Tab 600 mg" },
        { name: "Fexo Tab 120 mg" },
        { name: "Fexo Tab 60 mg" },
        { name: "Fexo Tab 180 mg" },
        { name: "Fexo Suspension 50 ml" },
        { name: "Filfresh Tab 3 mg" },
        { name: "Filwel Gold Tab" },
        { name: "Filwel Kids Syp 100 ml" },
        { name: "Filwel Silver Tab" },
        { name: "Filwel Teen Hm Tab" },
        { name: "Filwel Teen Hr Tab" },
        { name: "Flacol Chewable Tab 40 mg" },
        { name: "Flacol Pediatric Drop" },
        { name: "Flamfix Tab 750 mg" },
        { name: "Flamfix Tab 500 mg" },
        { name: "Flexi Tab 100 mg" },
        { name: "Flexi SR Tab 200 mg" },
        { name: "Flexilax Tab 5 mg" },
        { name: "Flexilax Tab 10 mg" },
        { name: "Fliban Tab 100 mg" },
        { name: "Flindof Tab 400 mg" },
        { name: "Flindof Tab 200 mg" },
        { name: "Flonasin Nasal Spray" },
        { name: "Flonaspray Nasal Spray" },
        { name: "Flugal Cap 50 mg" },
        { name: "Flugal Suspension 35 ml" },
        { name: "Flugal Cap 200 mg" },
        { name: "Flugal Cap 150 mg" },
        { name: "Flurizin Tab 5 mg" },
        { name: "Flurizin Tab 10 mg" },
        { name: "Fodexil Cap 500 mg" },
        { name: "Folita Tab 5 mg" },
        { name: "Fona Cream 0.1%" },
        { name: "Fona Gel 0.3%" },
        { name: "Fona Plus Gel" },
        { name: "Fosfomax Powder" },
        { name: "Frabex Cap 500 mg" },
        { name: "Fungidal Cream 2%" },
        { name: "Fungidal-HC Cream 2%+1%" },
        { name: "Fusid Tab 40 mg" },
        { name: "Fusid Injection 2 ml ampoule" },
        { name: "Fusid Plus Tab 40 mg+50 mg" },
        { name: "Fusid Plus Tab 20 mg+50 mg" },
        { name: "Fusitop-HC Cream 2%+1%" },
        { name: "G-Calbo Tab 500 mg" },
        { name: "G-Calbo DX Tab 600 mg" },
        { name: "Gabastar Tab 100 mg" },
        { name: "Gabastar Tab 300 mg" },
        { name: "Garlin Cap 10 mg" },
        { name: "Gefapix Tab 45 mg" },
        { name: "Gelora Oral Gel 2%" },
        { name: "Genacyn Ointment 0.1%" },
        { name: "Geston Tab 5 mg" },
        { name: "Gleazy Topical Gel" },
        { name: "Glympa Tab 25 mg+5 mg" },
        { name: "Glympa Tab 10 mg+5 mg" },
        { name: "Glysup Suppository 1 mg" },
        { name: "Glysup Suppository 4 gm" },
        { name: "Glysup Suppository 1.15 gm" },
        { name: "Glysup Suppository 2.30 gm" },
        { name: "Glysup Suppository 2 mg" },
        { name: "GOL Oral Solution 100 ml" },
        { name: "Gutfix Cap 8 mcg" },
        { name: "Gutfix Cap 24 mcg" },
        { name: "Gynepro Vaginal Suppository" },
        { name: "Halobet Ointment 0.05%" },
        { name: "Halobet Cream 0.05%" },
        { name: "Hemorif Tab 450 mg+50 mg" },
        { name: "Hemorif DS Tab 900 mg+100 mg" },
        { name: "Imotil Cap 2 mg" },
        { name: "Imotil Plus Tab 2 mg + 125 mg" },
        { name: "Intimate Tab 20 mg" },
        { name: "Intimate Tab 2.5 mg" },
        { name: "Intimate Tab 10 mg" },
        { name: "Intimate Tab 5 mg" },
        { name: "Iprex Respirator Solution 20 ml" },
        { name: "Iracet Tab 250 mg" },
        { name: "Iracet Tab 500 mg" },
        { name: "Iracet Oral Solution 50 ml" },
        { name: "Iracet XR Tab 500 mg" },
        { name: "Isotrin Cap 20 mg" },
        { name: "Isovent Tab 200 mcg" },
        { name: "Isovent Tab 600 mcg" },
        { name: "Itra Cap 100 mg" },
        { name: "Itra Tab 200 mg" },
        { name: "Itra Oral Solution 100 ml" },
        { name: "Ivanor Tab 7.5 mg" },
        { name: "Ivanor Tab 5 mg" },
        { name: "Iventi Eye Drop 0.5%" },
        { name: "Iventi-D Eye Drop" },
        { name: "Invent Tab 400 mg" },
        { name: "K-One MM Injection 2 mg/0.2 ml" },
        { name: "Ketoral Tab 200 mg" },
        { name: "Kop SR Cap 100 mg" },
        { name: "Lamicet Tab 50 mg" },
        { name: "Lanso Cap 30 mg" },
        { name: "Lanso D Cap 30 mg" },
        { name: "Lanso D Cap 60 mg" },
        { name: "Laxyl Tab 3 mg" },
        { name: "Lebac Cap 250 mg" },
        { name: "Lebac Cap 500 mg" },
        { name: "Lebac Suspension 100 ml" },
        { name: "Lebac Pediatric Drop 15 ml" },
        { name: "Lebac Forte Suspension 100 ml" },
        { name: "Lerozol Tab 2.5 mg" },
        { name: "Levocar Tab 330 mg" },
        { name: "Levostar Tab 1 mg" },
        { name: "Levostar Tab 2 mg" },
        { name: "Levostar Syp 50 ml" },
        { name: "Levostar Syp 100 ml" },
        { name: "Liglimet Tab 2.5 mg+500 mg" },
        { name: "Liglimet Tab 2.5 mg+850 mg" },
        { name: "Liglimet XR Tab 5 mg+1000 mg" },
        { name: "Linita Tab 5 mg" },
        { name: "Lipired Cap 200 mg" },
        { name: "Livacol Tab 5 mg" },
        { name: "Livacol Tab 10 mg" },
        { name: "Livwel Syp 100 ml" },
        { name: "Livwel Syp 200 ml" },
        { name: "LNC Tab 5 mg" },
        { name: "LNC Tab 10 mg" },
        { name: "Lofos Tab 667 mg" },
        { name: "Loracef Suspension 100 ml" },
        { name: "Loracef Pediatric Drop 15 ml" },
        { name: "Loratin Tab 10 mg" },
        { name: "Loratin Fast Tab 10 mg" },
        { name: "Lorno Tab 4 mg" },
        { name: "Lorno Tab 8 mg" },
        { name: "Lubgel Eye Drop 1%" },
        { name: "Lubtear Eye Drop 0.1%+0.3%" },
        { name: "Lulitop Cream 1%" },
        { name: "Lumertam Tab 20 mg+120 mg" },
        { name: "Luraprex Tab 40 mg" },
        { name: "Luraprex Tab 20 mg" },
        { name: "Lysivin Tab" },
        { name: "Maganta Plus Chewable Tab 480 mg+20 mg" },
        { name: "Maganta Plus Suspension 200 ml" },
        { name: "Magnide Tab 365 mg" },
        { name: "Maxbon Tab 150 mg" },
        { name: "Maxbon Kit Tab 150 mg & 400 mg" },
        { name: "Maxrin Cap 0.4 mg" },
        { name: "Maxrin D Cap 0.4 mg+0.5 mg" },
        { name: "Melano Cream" },
        { name: "Melixol Tab 0.5 mg+10 mg" },
        { name: "Menoral Tab 5 mg" },
        { name: "Merison Tab 6 mg" },
        { name: "Metaspray Nasal Spray" },
        { name: "Methicol Tab 500 mcg" },
        { name: "Methigic Tab 2 mg" },
        { name: "Methigic Tab 4 mg" },
        { name: "Methigic Tab 8 mg" },
        { name: "Methigic Tab 16 mg" },
        { name: "Methomol Tab 500 mg" },
        { name: "Methomol Tab 750 mg" },
        { name: "Mevin Tab 135 mg" },
        { name: "Mevin SR Cap 200 mg" },
        { name: "Mexlo Eye Drop 0.3%" },
        { name: "Migranil Tab 0.5 mg" },
        { name: "Migranil Tab 1.5 mg" },
        { name: "Minibet Tab 100 mg" },
        { name: "Mirader Tab 25 mg" },
        { name: "Mirakof Syp 100 ml" },
        { name: "Mirakof Pediatric Drop 15 ml" },
        { name: "Mirakof SR Tab 50 mg" },
        { name: "Mirapro Tab 7.5 mg" },
        { name: "Mirapro Tab 15 mg" },
        { name: "Montene Tab 4 mg" },
        { name: "Montene Tab 5 mg" },
        { name: "Montene Tab 10 mg" },
        { name: "Motigut Tab 10 mg" },
        { name: "Motigut Suspension 60 ml" },
        { name: "Motigut Pediatric Drop" },
        { name: "Moxacil Cap 250 mg" },
        { name: "Moxacil Cap 500 mg" },
        { name: "Moxacil Suspension 100 ml" },
        { name: "Moxacil Pediatric Drop 15 ml" },
        { name: "Moxaclav Tab 1 gm" },
        { name: "Moxaclav Suspension 100 ml" },
        { name: "Moxaclav Tab 375 mg" },
        { name: "Moxaclav Tab 625 mg" },
        { name: "Moxaclav Forte Suspension 50 ml" },
        { name: "Mucospel Syp 100 ml" },
        { name: "Multivit Plus Tab" },
        { name: "Myonil Tab 50 mg" },
        { name: "Nafodil Cap 100 mg" },
        { name: "Nasovap Suspension for Inhalation 100 ml" },
        { name: "Naurif Tab 1 mg" },
        { name: "Nebanol Ointment" },
        { name: "Nebanol Powder" },
        { name: "Nebanol Plus Ointment" },
        { name: "Nebita Tab 2.5 mg" },
        { name: "Nebita Tab 5 mg" },
        { name: "Nebita Plus Tab 5 mg+12.5 mg" },
        { name: "Neumig Tab 2.5 mg" },
        { name: "Neumig Tab 5 mg" },
        { name: "Neumig Tab 10 mg" },
        { name: "Neuro-B Tab" },
        { name: "Neuro-B Injection 3 ml ampoule" },
        { name: "Neurolep Tab 800 mg" },
        { name: "Neurolep Syp 100 ml" },
        { name: "Neurolin Cap 50 mg" },
        { name: "Neurolin Cap 75 mg" },
        { name: "Neurolin Cap 25 mg" },
        { name: "Neurolin CR 82.5 mg" },
        { name: "Neurolin CR 165 mg" },
        { name: "Nexum Cap 20 mg" },
        { name: "Nexum Cap 40 mg" },
        { name: "Nexum MUPS Tab 20 mg" },
        { name: "Nexum MUPS Tab 40 mg" },
        { name: "Nidipine SR Tab 20 mg" },
        { name: "Nimocal Tab 30 mg" },
        { name: "Nomi Tab 2.5 mg" },
        { name: "Nomi Nasal Spray" },
        { name: "Norpill 1 Tab 1.5 mg" },
        { name: "Norvis Tab 50 mg" },
        { name: "Norvis Syp 50 ml" },
        { name: "Ocof Syp 100 ml" },
        { name: "Ocubrom Eye Drop 0.07%" },
        { name: "Ofran Tab 8 mg" },
        { name: "Ofran Oral Solution 50 ml" },
        { name: "Olistat Cap 120 mg" },
        { name: "Olistat Cap 60 mg" },
        { name: "Olmecar Tab 20 mg" },
        { name: "Olmecar Tab 40 mg" },
        { name: "Olmecar Tab 10 mg" },
        { name: "Olmecar Plus Tab 20 mg+12.5 mg" },
        { name: "Orostar Cool Mint Mouthwash 120 ml" },
        { name: "Orostar Plus Mouthwash 120 ml" },
        { name: "Orostar Plus Mouthwash 250 ml" },
        { name: "Osmolax Oral Solution 100 ml" },
        { name: "Osmolax Oral Solution 200 ml" },
        { name: "Ostel-D Tab 70 mg" },
        { name: "Otic-4 Ear Drop" },
        { name: "Oxapro Tab 5 mg" },
        { name: "Oxapro Tab 10 mg" },
        { name: "Oxat Tab 20 mg" },
        { name: "Oxat Tab 10 mg" },
        { name: "Oxifun Cream 1%" },
        { name: "Oxifun Lotion 1% 30 ml" },
        { name: "Oxifyl CR Tab 400 mg" },
        { name: "Paloset Tab 0.5 mg" },
        { name: "Penrif Cream 30%+8%" },
        { name: "Penvik Tab 250 mg" },
        { name: "Penvik DS Tab 500 mg" },
        { name: "Penvik Forte Suspension 100 ml" },
        { name: "Peranel Tab 2 mg" },
        { name: "Peranel Tab 4 mg" },
        { name: "Perkidopa Tab 100 mg+ 10 mg" },
        { name: "Perkinil Tab 5 mg" },
        { name: "Perkinil Injection 10 mg" },
        { name: "Perkirol Tab 0.25 mg" },
        { name: "Perkirol Tab 2 mg" },
        { name: "Pevitin Cream 1%+0.1%" },
        { name: "Phylopen Cap 250 mg" },
        { name: "Phylopen Suspension 100 ml" },
        { name: "Phylopen Injection 500 mg/vial" },
        { name: "Phylopen DS Cap 500 mg" },
        { name: "Phylopen Forte Suspension 100 ml" },
        { name: "Prazolok Tab 1 mg" },
        { name: "Prazolok Tab 2 mg" },
        { name: "Prazolok ER Tab 2.5 mg" },
        { name: "Prazolok ER Tab 5 mg" },
        { name: "Prolert Cap 20 mg" },
        { name: "Promtil Tab 5 mg" },
        { name: "Pronor Tab 5 mg" },
        { name: "Prosalic Scalp Lotion" },
        { name: "Pylotrip Tab" },
        { name: "Pylotrip R Tab" },
        { name: "QTP Tab 100 mg" },
        { name: "QTP Tab 25 mg" },
        { name: "QTP XR Tab 200 mg" },
        { name: "Quinivir Tab 200 mg" },
        { name: "Rabeca Tab 20 mg" },
        { name: "Ranolin XR Tab 500 mg" },
        { name: "Rapiflo Cap 8 mg" },
        { name: "Rapiflo Cap 4 mg" },
        { name: "Rasalet Tab 0.5 mg" },
        { name: "Rasalet Tab 1 mg" },
        { name: "Rectocare Ointment 0.4%" },
        { name: "Relatro Cap 25 mg" },
        { name: "Remac Tab 500 mg" },
        { name: "Remac Suspension 60 ml" },
        { name: "Remus Ointment 0.03%" },
        { name: "Remus Ointment 0.1%" },
        { name: "Renorma Tab 2.5 mg" },
        { name: "Renustat Tab 50 mg" },
        { name: "Repres SR Tab 1.5 mg" },
        { name: "Retabac Ointment 1%" },
        { name: "Revira Tab 500 mg" },
        { name: "Revira Tab 1 gm" },
        { name: "Revocit Tab 210 mg" },
        { name: "Revolizer Inhaler" },
        { name: "Rex Tab 6 mg+200 mg+50 mg" },
        { name: "Rice ORS Powder" },
        { name: "Ripril Tab 2.5 mg" },
        { name: "Ripril Tab 5 mg" },
        { name: "Rivatig Cap 1.5 mg" },
        { name: "RivaXa Tab 10 mg" },
        { name: "Robic Tab 500 mg" },
        { name: "Rosuva Tab 5 mg" },
        { name: "Rosuva Tab 10 mg" },
        { name: "Rosuva Tab 20 mg" },
        { name: "Rozy Tab 0.5 mg+0.25 mg" },
        { name: "Rozy DS Tab 1 mg+0.5 mg" },
        { name: "Rupatrol Tab 10 mg" },
        { name: "Rutix Tab 200 mg" },
        { name: "Rutix Tab 400 mg" },
        { name: "Safyron Tab 10 mg" },
        { name: "Saga Tab 200 mg" },
        { name: "Salicid Cream 12%" },
        { name: "Scabex Cream 5%" },
        { name: "Seclo Cap 20 mg" },
        { name: "Seclo Cap 40 mg" },
        { name: "Seclo MUPS Tab 20 mg" },
        { name: "Secnid DS Tab 1000 mg" },
        { name: "Secrin Tab 1 mg" },
        { name: "Secrin Tab 2 mg" },
        { name: "Secrin Tab 3 mg" },
        { name: "Secrin Tab 4 mg" },
        { name: "Secrin M Tab 1 mg+500 mg" },
        { name: "Secrin M Tab 2 mg+500 mg" },
        { name: "Sedil Tab 5 mg" },
        { name: "Sedil Injection" },
        { name: "Siglimet Tab 50 mg+500 mg" },
        { name: "Siglimet Tab 50 mg+1000 mg" },
        { name: "Siglita Tab 50 mg" },
        { name: "Sodibar Tab 600 mg" },
        { name: "Solider Tab 10 mg" },
        { name: "Solider Tab 5 mg" },
        { name: "Solo Nasal Drop 0.9%" },
        { name: "SoloSpray Nasal Spray 0.9%" },
        { name: "Sonap Tab 250 mg" },
        { name: "Sonap Tab 500 mg" },
        { name: "Sopilax Oral Solution 100 ml" },
        { name: "Sopilax Tab 10 mg" },
        { name: "Splendora Scalp Solution 5% 60 ml" },
        { name: "SQ-Mycetin Eye Drop 0.5%" },
        { name: "Sulprex Inhaler" },
        { name: "Sulprex Respirator Solution" },
        { name: "Suprex Refill" },
        { name: "Sultolin Syp 100 ml" },
        { name: "Sultolin Inhaler 100 mcg" },
        { name: "Sultolin Inhalation Cap 200 mcg" },
        { name: "Sultolin Respirator Solution 20 ml" },
        { name: "Sultolin SR Tab 8 mg" },
        { name: "SunMask Cream" },
        { name: "Susten Tab 30 mg" },
        { name: "Suzyme Tab 325 mg" },
        { name: "Tebast Tab 10 mg" },
        { name: "Telmilok Tab 40 mg" },
        { name: "Telmilok Tab 80 mg" },
        { name: "Telmilok Plus Tab 40 mg+12.5 mg" },
        { name: "Terminex Tab 200 mg+200 mcg" },
        { name: "Tetrax Cap 500 mg" },
        { name: "Tezo Tab 200 mg" },
        { name: "Thyrin Tab 25 mcg" },
        { name: "Thyrin Tab 50 mcg" },
        { name: "Thyrin Tab 75 mcg" },
        { name: "Ticalog Tab 90 mg" },
        { name: "Ticamet Inhaler (25 mcg+125 mcg)/puff" },
        { name: "Ticamet Inhaler (25 mcg+250 mcg)/puff" },
        { name: "Ticamet Inhalation Cap 50 mcg+500 mcg" },
        { name: "Ticamet Inhalation Cap 50 mcg+250 mcg" },
        { name: "Ticamet Inhalation Cap 50 mcg+100 mcg" },
        { name: "Ticas Cream 0.05%" },
        { name: "Ticstop Tab 12.5 mg" },
        { name: "Ticstop Tab 25 mg" },
        { name: "Tilex Max Tab 750 mg+50 mg" },
        { name: "Timotor Tab 100 mg" },
        { name: "Tofator Tab 5 mg" },
        { name: "Togent Cream" },
        { name: "Tolfem Tab 200 mg" },
        { name: "Topicort Cream 1%" },
        { name: "Torax Tab 10 mg" },
        { name: "Torax Injection 60 mg/2 ml 2 ml ampoule" },
        { name: "Torax Injection 30 mg/ml 1 ml ampoule" },
        { name: "Torsid Tab 20 mg" },
        { name: "Torsid Tab 5 mg" },
        { name: "Tory Tab 60 mg" },
        { name: "Tory Tab 90 mg" },
        { name: "Tory Tab 120 mg" },
        { name: "Trelanti Inhalation Cap" },
        { name: "Trevox Tab 500 mg" },
        { name: "Trevox D Eye Drop" },
        { name: "Tridyl Tab 2 mg" },
        { name: "Tridyl Tab 5 mg" },
        { name: "Tridyl Syp 50 ml" },
        { name: "Trispray Nasal Spray" },
        { name: "Trupan Tab 20 mg" },
        { name: "Trupan Tab 40 mg" },
        { name: "Truxil Tab 30 mg+10 mg" },
        { name: "Tryptin Tab 10 mg" },
        { name: "Tryptin Tab 25 mg" },
        { name: "Tryptin Plus Tab 12.5 mg+5 mg" },
        { name: "Tusca Plus Syp 100 ml" },
        { name: "Tylace Tab 600 mg" },
        { name: "Ucol Tab 2 mg" },
        { name: "Ulpep Cap 500 mg" },
        { name: "Ulrif Suspension 200 ml" },
        { name: "Ultivent Inhalation Cap 110 mcg+50 mcg" },
        { name: "Ultivent-M Inhalation Cap" },
        { name: "Uriset Oral Solution 200 ml" },
        { name: "Urocure SR Cap" },
        { name: "Urso Tab 150 mg" },
        { name: "Urso Tab 300 mg" },
        { name: "Utal Tab 5 mg" },
        { name: "Valmor Tab 50 mg" },
        { name: "Valoate Syp 100 ml" },
        { name: "Valoate CR Tab 200 mg" },
        { name: "Valoate CR Tab 300 mg" },
        { name: "Valoate CR Tab 500 mg" },
        { name: "Vanprox Suspension 50 ml" },
        { name: "Vanprox Pediatric Drop 15 ml" },
        { name: "Vardamate Tab 10 mg" },
        { name: "Vardamate Tab 20 mg" },
        { name: "Vertina Plus Tab 25 mg+50 mg" },
        { name: "Vertina-D Tab 10 mg+10 mg" },
        { name: "Vertina-DX Tab 20 mg+20 mg" },
        { name: "Viglimet Tab 50 mg+500 mg" },
        { name: "Viglimet Tab 50 mg+850 mg" },
        { name: "Viglita Tab 50 mg" },
        { name: "Vigorex Tab 25 mg" },
        { name: "Vigorex Tab 50 mg" },
        { name: "Vigorex Tab 100 mg" },
        { name: "Vilanti Inhalation Cap 25 mcg+100 mcg" },
        { name: "Vilanti Inhalation Cap 25 mcg+200 mcg" },
        { name: "Viodin Solution 10% 15 ml" },
        { name: "Viodin Solution 100 ml" },
        { name: "Viodin Ointment 5%" },
        { name: "Viodin Mouthwash 1% 100 ml" },
        { name: "Virux Suspension 70 ml" },
        { name: "Virux Tab 200 mg" },
        { name: "Virux Tab 400 mg" },
        { name: "Virux Cream 5%" },
        { name: "Virux-HC Cream 5%+1%" },
        { name: "VOLINAC Gel 1%" },
        { name: "VOLINAC Max Gel 2%" },
        { name: "Voniza Tab 10 mg" },
        { name: "Voniza Tab 20 mg" },
        { name: "VonoKit Tab 20 mg+1000 mg+500 mg" },
        { name: "Vori Tab 200 mg" },
        { name: "Vori Tab 50 mg" },
        { name: "Waxnil Ear Drop 5%" },
        { name: "Xenole Tab 375 mg+20 mg" },
        { name: "Xenole Tab 500 mg+20 mg" },
        { name: "Xfin Cream 1%" },
        { name: "Xfin Tab 250 mg" },
        { name: "Xpos Tab 100 mg" },
        { name: "Xten Tab 20 mg" },
        { name: "Xylocon Nasal Drop 0.05%" },
        { name: "Xylocon Nasal Drop 0.025%" },
        { name: "Xylocon Nasal Spray 0.05%" },
        { name: "Zesup Syp 100 ml" },
        { name: "Zif Forte Cap" },
        { name: "Zif-A Tab" },
        { name: "Zif-CI Cap" },
        { name: "Zifolet Tab 5 mg+20 mg" },
        { name: "Ziliron-B Cap" },
        { name: "Zimax Cap 250 mg" },
        { name: "Zimax Suspension 15 ml" },
        { name: "Zimax Suspension 30 ml" },
        { name: "Zimax Suspension 50 ml" },
        { name: "Zimax Tab 500 mg" },
        { name: "Zolivox Tab 400 mg" },
        { name: "Zolivox Tab 600 mg" },
        { name: "Zolivox Suspension 100 ml" },
        { name: "Zox Tab 500 mg" },
        { name: "Zox Suspension 30 ml" },
        { name: "Sultolin Refill" },
        { name: "DK 4000" }
    ].sort((a, b) => a.name.localeCompare(b.name));

    const herbalItems = [
        { name: "Adovas Syp 100 ml" },
        { name: "Adovas Syp 200 ml" },
        { name: "AmCivit Syp 100 ml" },
        { name: "Antiscar Topical Gel" },
        { name: "Arubin Cap 500 mg" },
        { name: "Bacilax Cap 9 billion" },
        { name: "Betaburn Ointment 0.25 %" },
        { name: "Bioprem Cap 10 mcg" },
        { name: "Bioprem Cap 1 mcg" },
        { name: "Bioprem Cap 2.5 mcg" },
        { name: "Bioprem Cap 5 mcg" },
        { name: "Bolardi 250 mg" },
        { name: "Bolardi 500 mg" },
        { name: "Caripa Syp 200 ml" },
        { name: "Caripa Cap 250 mg" },
        { name: "Colmint Cap" },
        { name: "D-Sitol Cap 500 mg" },
        { name: "DK Cap" },
        { name: "Enerton Syp 200 ml" },
        { name: "Eprim Cap 500 mg" },
        { name: "Eprim Plus Cap 1000 mg" },
        { name: "Eredex Cap 5.4 mg" },
        { name: "Evit Cap 200 mg" },
        { name: "Evit Cap 400 mg" },
        { name: "Femony Cap" },
        { name: "Fitvit Cap" },
        { name: "Flemo Cap 40 mg" },
        { name: "Flemo Max Cap" },
        { name: "Flemo Plus Cap" },
        { name: "Freezy Nasal Inhaler" },
        { name: "Giloba Cap 60 mg" },
        { name: "Giloba Cap 120 mg" },
        { name: "Gintex Cap 500 mg" },
        { name: "Ispergul Eff. Powder 120 gm Container" },
        { name: "Ispergul Eff. Powder 3.5 gm sachet" },
        { name: "Jorvan Cap 500 mg" },
        { name: "Lecor Syp 200 ml" },
        { name: "Livolite Cap 200 mg" },
        { name: "Maximilk Cap" },
        { name: "Monera Syp 100 ml" },
        { name: "Navit Cap 500 mg" },
        { name: "Nilagel Cap 500 mg" },
        { name: "Ocubil Cap 160 mg" },
        { name: "Pepnor Syp 100 ml" },
        { name: "Probio R Cap 20 billion" },
        { name: "Probio Cap 4 billion" },
        { name: "Probio (For kids) Powder" },
        { name: "Redclov Cap 40 mg" },
        { name: "Reli Balm Cream" },
        { name: "Renacom Cap" },
        { name: "ResQ Cap 50 mg" },
        { name: "ResQ Cap 100 mg" },
        { name: "ResQ Cap 200 mg" },
        { name: "Revatol Syp 200 ml" },
        { name: "Silybin Cap 140 mg" },
        { name: "Toco Soft Cap" },
        { name: "Torel Muscle Rub" },
        { name: "Trumega Cap 1000 mg" },
        { name: "Uripam Cap 160 mg" },
        { name: "Urobery Cap 400 mg" },
        { name: "Urobery Syp 100 ml" },
        { name: "Zanthin Cap 2 mg" },
        { name: "Zanthin Cap 4 mg" }
    ].sort((a, b) => a.name.localeCompare(b.name));

    const currentItems = activeTab === 'General' ? generalItems : herbalItems;

    return (
        <div className='mx-3'>
            {/* Tabs */}
            <div className='flex gap-3 my-4'>
                <button
                    className={`btn ${activeTab === 'General' ? 'bg-blue-500 text-white' : 'bg-gray-200'}`}
                    onClick={() => setActiveTab('General')}
                >
                    General
                </button>
                <button
                    className={`btn ${activeTab === 'Herbal' ? 'bg-blue-500 text-white' : 'bg-gray-200'}`}
                    onClick={() => setActiveTab('Herbal')}
                >
                    Herbal
                </button>
            </div>

            <h2 className='text-lg font-medium'>{activeTab} Items</h2>
            <div className='my-2'>
                <hr />
            </div>

            <div>
                {currentItems.map(item => (
                    <div key={item.name} className='grid grid-cols-4 items-center gap-2'>
                        <p className='col-span-2'>{item.name}</p>
                        <input
                            className='border border-green-200 text-center py-3 px-2 rounded-lg'
                            type="number"
                            value={values[item.name] || ''}
                            onChange={(e) => handleChange(e, item.name)}
                            min="1"
                        />
                        <button
                            className={`btn text-white rounded-xl ${values[item.name] ? 'bg-purple-300' : 'bg-gray-300 cursor-not-allowed'}`}
                            disabled={!values[item.name]}
                            onClick={() => handleSelect(item.name, activeTab)}
                        >
                            Select
                        </button>
                    </div>
                ))}
            </div>

            <div className='mt-10'>
                <hr />
                <h2>Selected Items here:</h2>
                <ul>
                    {selectedItems.map((item, index) => (
                        <li key={index} className='grid grid-cols-4 items-center gap-2'>
                            <p className='col-span-2'>{item.name}</p>
                            <input
                                className='border border-green-200 py-3 px-2 rounded-lg text-center'
                                type="number"
                                value={item.quantity}
                                onChange={(e) => handleUpdateSelectedItem(e, item.name)}
                                min="1"
                            />
                        </li>
                    ))}
                </ul>
                <button className='btn bg-green-500 text-white my-3 rounded-xl' onClick={handleBuyNow}>
                    Generate Order Sheet
                </button>
            </div>
        </div>
    );
};

export default Square;